import type { Lesson } from "@/lib/course/types";

export const githubAdvanced: Lesson[] = [
  {
    id: "github-repository-inspection",
    track: "github",
    level: "basic",
    chapter: "github-repository",
    order: 8,
    title: "リポジトリの境界と状態を読む",
    summary: "管理対象、無視するファイル、statusの分類を深く読む",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "設定ファイルと一時ログまで記録候補に現れた",
      outcome: "管理境界を判断し、安全な状態だけを履歴へ進められる",
    },
    objectives: [
      { id: "repo-inspect", label: "追跡状態と無視対象を区別できる", conceptIds: ["git-tracked", "git-ignore", "git-status"] },
    ],
    slides: [
      {
        title: "リポジトリには境界がある",
        lead: "orders-appの.gitがあるフォルダーを基準に、その配下が一つの履歴管理単位になります。親フォルダーの別案件まで自動で含まれるわけではありません。どこでコマンドを実行しているかを確認します。",
        points: ["管理ルートを意識する", "入れ子の初期化は意図がなければ避ける", "statusのパスはルート基準で読む"],
        talk: [
          { speaker: "beginner", text: "どのフォルダーで実行しても、Gitが注文アプリを探してくれますか？" },
          { speaker: "engineer", text: "現在地から親へ管理情報を探します。別リポジトリで操作しないよう境界を確認します。" },
        ],
        diagram: "git-repository",
        storyBeat: "problem",
        objectiveId: "repo-inspect",
        conceptIds: ["git-tracked"],
      },
      {
        title: "無視は秘密を消す仕組みではない",
        lead: "生成ログや依存物は.gitignoreへ規則を書き、通常の候補から外します。ただし、すでに追跡済みのファイルには後から規則を書くだけでは効きません。また、秘密を一度コミットすると無視設定では履歴から消せません。",
        points: ["生成物と個人環境ファイルを除外する", "秘密情報は最初からコミットしない", "追跡済みかどうかを区別する"],
        talk: [
          { speaker: "beginner", text: "APIキーを記録した後で無視すれば、安全になりますか？" },
          { speaker: "engineer", text: "履歴には残ります。鍵の失効・再発行など別の対応が必要です。" },
        ],
        diagram: "git-repository",
        code: `.env
logs/
node_modules/`,
        storyBeat: "trace",
        objectiveId: "repo-inspect",
        conceptIds: ["git-ignore"],
      },
      {
        title: "short statusで分類を素早く読む",
        lead: "短い形式では左列がステージ、右列が作業ツリーの状態です。同じファイルに追加済み変更と、その後の未追加編集が同居することもあります。記号だけ暗記せず、二つの置き場として読みます。",
        points: ["左は次のコミット候補", "右はまだ作業ツリーだけ", "不明な状態は通常形式で見直す"],
        talk: [
          { speaker: "beginner", text: "一つのファイルに二つ記号が出るのは二重登録ですか？" },
          { speaker: "engineer", text: "追加した後にまた編集すると、二段階の差分が同時に存在します。" },
        ],
        diagram: "git-staging",
        code: `MM app.js
?? debug.log`,
        storyBeat: "resolution",
        objectiveId: "repo-inspect",
        conceptIds: ["git-status"],
      },
    ],
    questions: [
      {
        id: "repo-inspect-secret",
        slide: 0,
        prompt: "orders-appを別案件と混ぜず、一つの履歴管理単位として扱う考え方を選んでください。",
        kind: "choice",
        options: ["管理ルートとコマンドの現在地を確認する", "親フォルダーの別案件も同じ履歴へ入れる", "各ファイルで別々のリポジトリを作る", "現在地を見ず常に親を管理対象にする"],
        answer: "管理ルートとコマンドの現在地を確認する",
        explain: ".gitがある管理ルートと現在地を確認し、別リポジトリを誤操作しないようにします。",
        hints: ["履歴管理には基準となる場所があります。", "コマンドを実行する現在地も確認します。", "管理ルートと現在地を含む選択肢です。"],
        objectiveId: "repo-inspect",
        conceptIds: ["git-tracked"],
        gitInitialState: { files: { ".gitignore": ".env\n", "app.js": "start();" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "repo-inspect-untracked",
        slide: 2,
        prompt: "短い状態表示で、まだ追跡されていないファイルを示す2文字を入力してください。",
        kind: "input",
        answer: "??",
        explain: "短い表示では??が未追跡ファイルを示します。",
        hints: ["変更種別がまだ確定していません。", "同じ記号を二つ並べます。", "疑問を表す記号です。"],
        objectiveId: "repo-inspect",
        conceptIds: ["git-status"],
        gitInitialState: { files: { "debug.log": "temporary" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "repo-inspect-ignore",
        slide: 1,
        prompt: "注文アプリの秘密情報を除外する.gitignoreを、次の履歴へ含められる状態にしてください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: "git add .gitignore",
        explain: "無視規則自体はチームで共有するため、通常のファイルとしてステージします。",
        hints: ["規則ファイルそのものは履歴へ残します。", "次のコミット候補へ選ぶ操作です。", "対象の隠しファイル名を引数にします。"],
        objectiveId: "repo-inspect",
        conceptIds: ["git-ignore", "git-status"],
        gitInitialState: { files: { ".gitignore": ".env\nlogs/\n", "logs/debug.log": "temporary" }, branch: "main" },
        gitAssertions: [{ kind: "staged", path: ".gitignore" }],
      },
    ],
  },
  {
    id: "github-commit-history",
    track: "github",
    level: "basic",
    chapter: "github-commit",
    order: 9,
    title: "logとdiffで変更理由をたどる",
    summary: "記録前後の差分を分け、読みやすい履歴を作る",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "注文合計が変わった理由を、現在のファイルだけでは説明できない",
      outcome: "差分と履歴から、いつ・なぜ変わったかを追跡できる",
    },
    objectives: [
      { id: "history-read", label: "diffとlogを使い分け、意図のあるコミットを作れる", conceptIds: ["git-diff", "git-log", "commit-message"] },
    ],
    slides: [
      {
        title: "diffはまだ記録していない差を見る",
        lead: "合計計算を直したら、コミット前に差分を読みます。通常のdiffは作業ツリーとステージの差、staged向けの表示はステージと直前の履歴との差です。どの境界を見るかで内容が変わります。",
        points: ["追加前と追加後で見る差が違う", "不要なデバッグ出力を見つける", "差分を読んでから記録する"],
        talk: [
          { speaker: "beginner", text: "追加後に通常の差分が空なら、変更が消えましたか？" },
          { speaker: "engineer", text: "ステージへ移った可能性があります。比較している二つの場所を確認します。" },
        ],
        diagram: "git-staging",
        storyBeat: "problem",
        objectiveId: "history-read",
        conceptIds: ["git-diff"],
      },
      {
        title: "logはコミットの連なりを読む",
        lead: "履歴には識別子、作者、日時、メッセージがあります。一行表示やグラフ表示を使うと、注文機能の流れや枝分かれを短く確認できます。識別子はコミットを指す住所として使えます。",
        points: ["新しい記録から並ぶ", "短縮識別子でも多くの操作に使える", "グラフで分岐と統合を見る"],
        talk: [
          { speaker: "beginner", text: "ファイルの最終形だけ見れば、理由も分かりますよね？" },
          { speaker: "engineer", text: "何を変えたかは見えても、なぜ変えたかはメッセージやPRが手掛かりになります。" },
        ],
        diagram: "git-history",
        storyBeat: "trace",
        objectiveId: "history-read",
        conceptIds: ["git-log"],
      },
      {
        title: "一つのコミットは一つの説明",
        lead: "税計算修正とボタン色変更を別々に記録すれば、レビューや取り消しがしやすくなります。大きさに絶対値はありませんが、「この変更は何のためか」を一文で説明できるまとまりを目指します。",
        points: ["無関係な変更を分ける", "命令形などチームの規約へ揃える", "テスト可能な単位を保つ"],
        talk: [
          { speaker: "beginner", text: "細かければ、一行ずつコミットする方が良いですか？" },
          { speaker: "engineer", text: "行数ではなく意図のまとまりです。関連する変更とテストを一緒にします。" },
        ],
        diagram: "git-history",
        storyBeat: "resolution",
        objectiveId: "history-read",
        conceptIds: ["commit-message"],
      },
    ],
    questions: [
      {
        id: "history-read-boundary",
        slide: 0,
        prompt: "追加済みの内容と直前のコミットとの差を確認したいとき、見る対象を選んでください。",
        kind: "choice",
        options: ["ステージ済み差分", "未追跡ファイルだけ", "リモートURL", "Issue一覧"],
        answer: "ステージ済み差分",
        explain: "次回コミットされる内容を確認するには、ステージと直前の履歴を比較します。",
        hints: ["次回の箱に入った内容です。", "作業ツリーだけの変更ではありません。", "追加後の差を表す選択肢です。"],
        objectiveId: "history-read",
        conceptIds: ["git-diff"],
        gitInitialState: { files: { "total.js": "export const total = () => 0;" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "history-read-address",
        slide: 1,
        prompt: "特定のコミットを指す住所として使う値の名前を漢字4文字で入力してください。",
        kind: "input",
        answer: "識別子",
        explain: "各コミットの識別子を使うと、履歴上の特定地点を指定できます。",
        hints: ["作者名や日時ではありません。", "個々の記録を区別します。", "「識別」に一文字を足した語です。"],
        objectiveId: "history-read",
        conceptIds: ["git-log"],
        gitInitialState: { files: { "total.js": "export const total = () => 0;" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "history-read-commit",
        slide: 2,
        prompt: "total.jsだけを選び、「合計の税計算を修正」という一つの履歴にしてください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: `git add total.js
git commit -m "合計の税計算を修正"`,
        explain: "目的に関係するファイルだけを選び、理由が伝わる単位で確定します。",
        hints: ["先に対象を次の記録へ選びます。", "その後、履歴として確定します。", "説明文はメッセージ用オプションへ渡します。"],
        objectiveId: "history-read",
        conceptIds: ["git-diff", "commit-message"],
        gitInitialState: { files: { "total.js": "export const total = (n) => n * 1.1;", "button.css": "color: blue;" }, branch: "main" },
        gitAssertions: [{ kind: "staged", path: "total.js" }, { kind: "commit-count", count: 1 }],
      },
    ],
  },
  {
    id: "github-branch-merge",
    track: "github",
    level: "middle",
    chapter: "github-branch",
    order: 10,
    title: "履歴の形を見てmergeする",
    summary: "fast-forwardとマージコミットを理解し、統合方向を判断する",
    minutes: 20,
    story: {
      project: "注文管理アプリ",
      incident: "検索機能と在庫表示が別々に進み、統合順を説明できない",
      outcome: "履歴グラフと現在地を確認して、安全に機能枝を統合できる",
    },
    objectives: [
      { id: "merge-model", label: "統合方向と履歴の形を説明してmergeできる", conceptIds: ["fast-forward", "merge-commit", "git-merge"] },
    ],
    slides: [
      {
        title: "枝分かれがなければ目印が進む",
        lead: "mainから検索枝を作った後、main側に新しい記録がなければ、統合時にmainの目印を検索枝の先へ進めるだけで済みます。これがfast-forwardです。",
        points: ["履歴が一直線になる", "変更内容が小さいという意味ではない", "統合前にグラフを確認する"],
        talk: [
          { speaker: "beginner", text: "高速に処理されるマージだから、この名前ですか？" },
          { speaker: "engineer", text: "速度より履歴の形です。枝の先まで目印を早送りするイメージです。" },
        ],
        diagram: "git-branch",
        storyBeat: "problem",
        objectiveId: "merge-model",
        conceptIds: ["fast-forward"],
      },
      {
        title: "両側が進めば統合地点を作る",
        lead: "mainにも在庫修正が入り、検索枝にもコミットがある場合、二つの親を持つマージコミットで流れを結びます。内容が衝突しなければ自動で統合できます。",
        points: ["二つの開発線が合流した事実を残す", "自動統合と競合なしは同義ではない", "テストで組み合わせを確認する"],
        talk: [
          { speaker: "beginner", text: "競合しなければ、動作確認も不要ですか？" },
          { speaker: "engineer", text: "文字列として統合できても、機能の組み合わせが正しいとは限りません。" },
        ],
        diagram: "git-branch",
        storyBeat: "trace",
        objectiveId: "merge-model",
        conceptIds: ["merge-commit"],
      },
      {
        title: "受け取り側で統合し、結果を検証する",
        lead: "feature/searchをmainへ入れるなら、mainへ移ってから検索枝を指定します。統合後はstatus、履歴、テストを確認します。模擬環境なので、操作はローカルの学習用履歴だけを変えます。",
        points: ["現在地が統合先", "統合後に注文検索テストを実施", "不要になった枝は確認後に整理"],
        talk: [
          { speaker: "beginner", text: "枝名を二つ並べて方向を指定しますか？" },
          { speaker: "engineer", text: "現在の枝が受け取り側です。だから先にswitchして方向を明確にします。" },
        ],
        diagram: "git-branch",
        storyBeat: "resolution",
        objectiveId: "merge-model",
        conceptIds: ["git-merge"],
      },
    ],
    questions: [
      {
        id: "merge-model-ff",
        slide: 0,
        prompt: "統合先が枝分かれ後に進んでいない場合の履歴変化として適切なものを選んでください。",
        kind: "choice",
        options: ["統合先の目印が作業枝の先へ進む", "統合のたびに必ず競合状態が発生する", "すべてのファイルを別名で複製する", "登録済みのリモート設定が削除される"],
        answer: "統合先の目印が作業枝の先へ進む",
        explain: "一直線の履歴なら、統合先ブランチの参照を先へ進めるfast-forwardが可能です。",
        hints: ["新しい分岐点を作る必要がありません。", "履歴は一直線です。", "目印の移動を説明する選択肢です。"],
        objectiveId: "merge-model",
        conceptIds: ["fast-forward"],
        gitInitialState: { files: { "search.js": "search();" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "merge-model-parent",
        slide: 1,
        prompt: "二つの開発線を結ぶコミットが持つ親の数を半角数字で入力してください。",
        kind: "input",
        answer: "2",
        explain: "マージコミットは通常、統合前の両方の先端を親として持ちます。",
        hints: ["一方だけでは合流を表せません。", "main側と作業枝側を数えます。", "1より一つ大きい数です。"],
        objectiveId: "merge-model",
        conceptIds: ["merge-commit"],
        gitInitialState: { files: { "search.js": "search();" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "merge-model-run",
        slide: 2,
        prompt: "注文検索を実装したfeature/searchからmainへ移り、その成果を統合してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: `git switch main
git merge feature/search`,
        explain: "受け取り側へ先に移り、そこへ作業枝を指定して統合します。",
        hints: ["最初に成果を受け取る枝へ移ります。", "次に統合操作を行います。", "二行目には取り込む側の枝名を渡します。"],
        objectiveId: "merge-model",
        conceptIds: ["git-switch", "git-merge"],
        gitInitialState: { branch: "feature/search", branches: ["main"] },
        gitAssertions: [{ kind: "branch", name: "main" }, { kind: "merged", branch: "feature/search" }],
      },
    ],
  },
  {
    id: "github-remote-sync",
    track: "github",
    level: "middle",
    chapter: "github-remote",
    order: 11,
    title: "fetchとpullで共有履歴を取り込む",
    summary: "取得と統合を分け、push拒否の理由を読み解く",
    minutes: 20,
    story: {
      project: "注文管理アプリ",
      incident: "仲間の在庫修正が先に共有され、自分のpushが拒否された",
      outcome: "共有側の更新を確認し、手元へ安全に統合してから共有できる",
    },
    objectives: [
      { id: "sync-flow", label: "fetchとpullの違いを説明し、共有更新を取り込める", conceptIds: ["git-fetch", "git-pull", "non-fast-forward"] },
    ],
    slides: [
      {
        title: "fetchは共有側の地図を更新する",
        lead: "仲間の変更をいきなり作業枝へ混ぜたくない場合、まずfetchで共有側の履歴情報を取得します。作業ツリーや現在のローカルブランチは自動で統合されません。この教材では取得結果も模擬データです。",
        points: ["通信部分はシミュレーター内で完結", "リモート追跡ブランチが更新される", "差を確認してから統合できる"],
        talk: [
          { speaker: "beginner", text: "取得したらapp.jsもすぐ仲間版になりますか？" },
          { speaker: "engineer", text: "fetchだけなら現在の作業内容へは統合しません。まず比較できます。" },
        ],
        diagram: "git-remote",
        storyBeat: "problem",
        objectiveId: "sync-flow",
        conceptIds: ["git-fetch"],
      },
      {
        title: "pullは取得して現在枝へ統合する",
        lead: "pullは共有側の更新を取得し、現在の枝へ統合する一連の操作です。便利な分、未コミット変更や現在地を確認せず実行すると状況が複雑になります。",
        points: ["実行前にstatusを見る", "現在枝の追跡先を確認する", "チームの統合方針を揃える"],
        talk: [
          { speaker: "beginner", text: "どの枝にいてもmainが更新されますか？" },
          { speaker: "engineer", text: "基本は現在の枝へ取り込みます。現在地と追跡先を確認してください。" },
        ],
        diagram: "git-remote",
        storyBeat: "trace",
        objectiveId: "sync-flow",
        conceptIds: ["git-pull"],
      },
      {
        title: "push拒否は上書きを防ぐ安全装置",
        lead: "共有側が手元より先に進んでいると、通常のpushは拒否されます。仲間の履歴を失わないためです。先に取得・統合・テストし、その後で再共有します。理由なく強制送信してはいけません。",
        points: ["拒否メッセージを読む", "共有更新を手元へ取り込む", "統合後にテストして再push"],
        talk: [
          { speaker: "beginner", text: "拒否されたら強制すれば、自分の最新版に揃いますよね？" },
          { speaker: "engineer", text: "仲間の履歴を失う危険があります。まず相手側の更新を理解して統合します。" },
        ],
        diagram: "git-remote",
        storyBeat: "resolution",
        objectiveId: "sync-flow",
        conceptIds: ["non-fast-forward"],
      },
    ],
    questions: [
      {
        id: "sync-flow-fetch",
        slide: 0,
        prompt: "作業ツリーへすぐ統合せず、共有側の更新情報だけを先に得たい場合の操作を選んでください。",
        kind: "choice",
        options: ["fetch", "commit", "init", "branch"],
        answer: "fetch",
        explain: "fetchは共有履歴を取得し、現在のローカルブランチへ自動統合しません。",
        hints: ["取得と統合を分けます。", "現在のファイルをすぐ変えません。", "英語で取ってくる意味の操作です。"],
        objectiveId: "sync-flow",
        conceptIds: ["git-fetch"],
        gitInitialState: { branch: "main", remote: "origin" },
        gitAssertions: [{ kind: "remote", name: "origin" }],
      },
      {
        id: "sync-flow-protection",
        slide: 2,
        prompt: "共有側が先行しているとき、通常の送信拒否が守っているものを漢字2文字で入力してください。",
        kind: "input",
        answer: "履歴",
        explain: "拒否は共有側にある仲間のコミットを上書きで失わないようにします。",
        hints: ["現在の一ファイルだけではありません。", "コミットの連なりです。", "この講座で記録と呼んできたものです。"],
        objectiveId: "sync-flow",
        conceptIds: ["non-fast-forward"],
        gitInitialState: { files: { "stock.js": "export const stock = 3;" }, branch: "main", remote: "origin" },
        gitAssertions: [{ kind: "remote", name: "origin" }],
      },
      {
        id: "sync-flow-pull",
        slide: 1,
        prompt: "現在の注文アプリのmainへ、模擬originのmainにある更新を取得して統合してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: "git pull origin main",
        explain: "共有側とブランチを明示すると、取得した更新を現在のmainへ統合できます。実通信はありません。",
        hints: ["取得と統合を一度に行う操作です。", "共有先の短い名前を指定します。", "最後に取り込む共有ブランチ名を続けます。"],
        objectiveId: "sync-flow",
        conceptIds: ["git-pull"],
        gitInitialState: { branch: "main", remote: "origin" },
        gitAssertions: [{ kind: "remote-tracked", remote: "origin", branch: "main" }],
      },
    ],
  },
  {
    id: "github-pr-review",
    track: "github",
    level: "advanced",
    chapter: "github-pr",
    order: 12,
    title: "ghでリポジトリとPRを運用する",
    summary: "repo、pr status、レビュー確認、mergeまでを安全につなぐ",
    minutes: 22,
    story: {
      project: "注文管理アプリ",
      incident: "複数のPRが並び、どれが確認済みで統合可能か分からない",
      outcome: "CLIで状態を読み、条件を満たすPRだけを統合できる",
    },
    objectives: [
      { id: "pr-review", label: "ghでリポジトリとPRの状態を確認し、安全に統合できる", conceptIds: ["gh-repo", "gh-pr-status", "gh-pr-merge"] },
    ],
    slides: [
      {
        title: "repoコマンドは共有リポジトリを扱う",
        lead: "gh repoはリポジトリの作成、表示、複製などGitHubサービス側の操作をまとめます。git initとは役割が違います。この教材ではrepo createも架空の共有先を作るだけで、実アカウントやネットワークへ接続しません。",
        points: ["ローカル初期化とサービス側作成を分ける", "公開範囲を確認する", "実秘密情報を教材へ入力しない"],
        talk: [
          { speaker: "beginner", text: "repo createは手元の.gitを作る操作ですか？" },
          { speaker: "engineer", text: "主にサービス側のリポジトリを作る操作です。ローカル初期化とは分けて考えます。" },
        ],
        diagram: "git-pr",
        code: `gh repo create orders-app --private
# 教材では架空の共有先だけを作る`,
        storyBeat: "problem",
        objectiveId: "pr-review",
        conceptIds: ["gh-repo"],
      },
      {
        title: "pr statusで自分に関係する提案を見る",
        lead: "作成したPR、レビュー依頼中のPR、確認が必要な状態を一覧できます。さらに個別表示やchecksで、説明、レビュー、テスト結果を確認します。状態を見る操作は統合操作ではありません。",
        points: ["PR一覧と個別詳細を使い分ける", "レビューと自動チェックを見る", "差分の向きと対象Issueを確認する"],
        talk: [
          { speaker: "beginner", text: "一覧に緑があれば、内容を読まず統合してよいですか？" },
          { speaker: "engineer", text: "自動検査は一部の条件です。差分、レビュー、要件も確認します。" },
        ],
        diagram: "git-pr",
        code: `gh pr status
gh pr checks 42`,
        storyBeat: "trace",
        objectiveId: "pr-review",
        conceptIds: ["gh-pr-status"],
      },
      {
        title: "pr mergeは最後の意思決定",
        lead: "承認、テスト、保護ルールを満たしたら統合します。merge、squash、rebaseなど履歴の残し方はチーム方針に従います。ブランチ削除を同時に行う場合も、不要になったことを確認します。",
        points: ["チェック通過だけでなく要件を確認", "履歴方式をチームで統一", "統合後のmainも監視する"],
        talk: [
          { speaker: "beginner", text: "自分のPRならレビュー前でも統合してよいですか？" },
          { speaker: "engineer", text: "権限があってもチームの保護ルールと承認条件に従います。" },
        ],
        diagram: "git-pr",
        code: `gh pr merge 42 --squash --delete-branch`,
        storyBeat: "resolution",
        objectiveId: "pr-review",
        conceptIds: ["gh-pr-merge"],
      },
    ],
    questions: [
      {
        id: "pr-review-check",
        slide: 0,
        prompt: "gh repoとgit initの役割の違いとして適切な説明を選んでください。",
        kind: "choice",
        options: ["gh repoは共有側、git initは手元を扱う", "両方とも公開リポジトリだけを作成するための操作", "両方ともPRの承認と統合だけを行うための操作", "git initはログイン認証だけを行うための操作"],
        answer: "gh repoは共有側、git initは手元を扱う",
        explain: "gh repoは共有サービス側の操作、git initはローカルの履歴管理開始に使います。",
        hints: ["共有サービス側と手元を分けます。", "二つのコマンドは操作する場所が異なります。", "GitHub側と手元を対比した選択肢です。"],
        objectiveId: "pr-review",
        conceptIds: ["gh-repo"],
        gitInitialState: { files: { "search.js": "search();" }, branch: "feature/search", remote: "origin" },
        gitAssertions: [{ kind: "pr-open", base: "main", head: "feature/search" }],
      },
      {
        id: "pr-review-command",
        slide: 1,
        prompt: "自分に関係するPRの状態一覧を見るサブコマンド名を英字で入力してください。",
        kind: "input",
        answer: "status",
        explain: "gh pr配下の状態確認では、作成済みやレビュー依頼中のPRをまとめて見られます。",
        hints: ["変更を加えない確認操作です。", "Gitでも現在状態を見るときに使う語です。", "先頭はs、末尾はsです。"],
        objectiveId: "pr-review",
        conceptIds: ["gh-pr-status"],
        gitInitialState: { files: { "search.js": "search();" }, branch: "feature/search", remote: "origin" },
        gitAssertions: [{ kind: "pr-open", base: "main", head: "feature/search" }],
      },
      {
        id: "pr-review-merge",
        slide: 2,
        prompt: "模擬PR 42の確認が完了しました。履歴を一つにまとめる方式で統合し、作業ブランチも削除してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "gh pr status\n",
        answer: `gh pr status
gh pr merge 42 --squash --delete-branch`,
        explain: "状態を確認してから、チーム方針のsquash方式で統合し、不要な枝を整理します。操作は模擬です。",
        hints: ["最初にPR一覧の状態を確認します。", "次に指定番号を統合する操作です。", "履歴方式と枝削除の二つのオプションを付けます。"],
        objectiveId: "pr-review",
        conceptIds: ["gh-pr-status", "gh-pr-merge"],
        gitInitialState: { files: { "search.js": "search();" }, branch: "feature/search", remote: "origin" },
        gitAssertions: [{ kind: "clean" }],
      },
    ],
  },
  {
    id: "github-conflict-recovery",
    track: "github",
    level: "advanced",
    chapter: "github-conflict",
    order: 13,
    title: "競合を予防し、途中から安全に戻る",
    summary: "小さな同期、テスト、abortで競合対応を制御する",
    minutes: 22,
    story: {
      project: "注文管理アプリ",
      incident: "大きな機能枝で多数の競合が起き、途中の編集も混ざって判断不能になった",
      outcome: "統合を中止して開始前へ戻し、競合を小さく解き直せる",
    },
    objectives: [
      { id: "conflict-recovery", label: "競合対応の継続・中止を判断し、解決後を検証できる", conceptIds: ["conflict-prevention", "merge-abort", "conflict-test"] },
    ],
    slides: [
      {
        title: "競合は小さく同期して減らす",
        lead: "長期間mainを取り込まない大きな枝ほど、同じ場所が変わる機会が増えます。責務を分けた小さなPR、定期的な同期、共通ファイル変更の相談で競合の量を減らせます。",
        points: ["短命な作業枝を保つ", "共通設定の変更は先に共有", "機械的な整形と機能変更を分ける"],
        talk: [
          { speaker: "beginner", text: "競合を完全にゼロにするルールはありますか？" },
          { speaker: "engineer", text: "共同編集では起こり得ます。量を減らし、解決しやすい単位にするのが現実的です。" },
        ],
        diagram: "git-conflict",
        storyBeat: "problem",
        objectiveId: "conflict-recovery",
        conceptIds: ["conflict-prevention"],
      },
      {
        title: "判断できないときはabortで戻る",
        lead: "統合中に前提を間違えた、未準備の変更が多い、と気づいたら無理に完成させず中止できます。abortは統合開始前の状態へ戻すための操作です。中止前にもstatusで状況を確認します。",
        points: ["競合ファイルを消して逃げない", "開始前へ戻って情報を集め直す", "中止と変更破棄を混同しない"],
        talk: [
          { speaker: "beginner", text: "途中まで直したので、分からなくてもコミットした方が得ですか？" },
          { speaker: "engineer", text: "誤った完成形を残すより、一度戻って仕様と差分を整理する選択があります。" },
        ],
        diagram: "git-conflict",
        storyBeat: "trace",
        objectiveId: "conflict-recovery",
        conceptIds: ["merge-abort"],
      },
      {
        title: "マーカー消去だけでは解決完了ではない",
        lead: "構文が通っても、送料と割引の組み合わせが壊れることがあります。差分確認、マーカー検索、単体テスト、注文フローの確認を行い、両方の変更意図が保たれたかをレビューします。",
        points: ["構文と業務仕様の両方を検証", "解決コミットに判断理由を残す", "必要なら変更者二人でペア確認"],
        talk: [
          { speaker: "beginner", text: "印がなくなればGitは成功扱いなので、テストも成功ですよね？" },
          { speaker: "engineer", text: "Gitが知るのは文字の状態です。注文仕様の正しさはテストとレビューで確かめます。" },
        ],
        diagram: "git-conflict",
        storyBeat: "resolution",
        objectiveId: "conflict-recovery",
        conceptIds: ["conflict-test"],
      },
    ],
    questions: [
      {
        id: "conflict-recovery-choice",
        slide: 0,
        prompt: "大きな競合を起こりにくくする進め方を選んでください。",
        kind: "choice",
        options: ["小さなPRで進め、mainを定期的に取り込む", "長期間すべての変更を一つの枝へためる", "共通設定を相談せず同時に書き換える", "整形と機能変更を常に同じ差分へ混ぜる"],
        answer: "小さなPRで進め、mainを定期的に取り込む",
        explain: "作業を小さく保ち、mainとの差を定期的に縮めると競合を減らせます。",
        hints: ["変更の差が大きいほど衝突箇所も増えます。", "短い周期で差を小さくします。", "小さなPRと定期同期を含む選択肢です。"],
        objectiveId: "conflict-recovery",
        conceptIds: ["conflict-prevention"],
        gitInitialState: { files: { "fee.js": "conflicted" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "conflict-recovery-quality",
        slide: 2,
        prompt: "Gitだけでは判断できず、解決後に別途確認すべき正しさを漢字4文字で入力してください。",
        kind: "input",
        answer: "業務仕様",
        explain: "Gitはテキスト統合を扱いますが、注文計算が要件どおりかはテストやレビューで確認します。",
        hints: ["構文だけでは不足です。", "注文や送料のルールです。", "仕事上の決まりを表す語です。"],
        objectiveId: "conflict-recovery",
        conceptIds: ["conflict-test"],
        gitInitialState: { files: { "fee.js": "const fee = calculateFee(order);" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "conflict-recovery-abort",
        slide: 1,
        prompt: "注文送料で進行中のマージを取りやめ、開始前の状態へ戻してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: "git merge --abort",
        explain: "統合を中止すると、判断材料を集めてから安全にやり直せます。",
        hints: ["統合サブコマンドの機能です。", "新しいコミットは作りません。", "中止を表す長いオプションを指定します。"],
        objectiveId: "conflict-recovery",
        conceptIds: ["merge-abort"],
        gitInitialState: { files: { "fee.js": "<<<<<<< HEAD\nconst fee = 500;\n=======\nconst fee = calc();\n>>>>>>> feature/fee" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
    ],
  },
  {
    id: "github-automation-guardrails",
    track: "github",
    level: "advanced",
    chapter: "github-automation",
    order: 14,
    title: "Actionsと保護ルールでmainを守る",
    summary: "自動検査と人の承認を組み合わせ、継続的な品質管理を作る",
    minutes: 22,
    story: {
      project: "注文管理アプリ",
      incident: "テスト未実行の変更がmainへ入り、注文確定ボタンが動かなくなった",
      outcome: "PRごとの自動検査と保護ルールで、統合前に問題を止められる",
    },
    objectives: [
      { id: "automation-guard", label: "Actionsとブランチ保護の役割を分けて説明できる", conceptIds: ["github-actions", "workflow-check", "branch-protection"] },
    ],
    slides: [
      {
        title: "Actionsは決めた手順を自動実行する",
        lead: "PRやpushをきっかけに、依存関係の準備、型検査、テストを自動実行できます。workflowはいつ、どの環境で、何を行うかをYAMLで定義します。この教材では実GitHub runnerを使わず、結果を模擬表示します。",
        points: ["イベントが開始条件", "jobの中でstepを順に実行", "機密値をログへ出さない"],
        talk: [
          { speaker: "beginner", text: "Actionsがあれば、開発者は手元でテストしなくてよいですか？" },
          { speaker: "engineer", text: "自動検査は最後の網です。手元の短いフィードバックも併用します。" },
        ],
        diagram: "git-actions",
        storyBeat: "problem",
        objectiveId: "automation-guard",
        conceptIds: ["github-actions"],
      },
      {
        title: "失敗したチェックは原因箇所から読む",
        lead: "赤い印だけで「Actionsが壊れた」と決めず、失敗したjobと最初の有意味なエラーを読みます。注文テストの期待値、型エラー、環境差など原因を分けます。再実行だけで隠さないことが大切です。",
        points: ["どのstepで止まったか確認", "最初の原因エラーを読む", "偶発的失敗も記録して改善する"],
        talk: [
          { speaker: "beginner", text: "再実行で緑になれば原因調査は不要ですか？" },
          { speaker: "engineer", text: "不安定なテストなら再発します。なぜ結果が揺れたかを追います。" },
        ],
        diagram: "git-actions",
        storyBeat: "trace",
        objectiveId: "automation-guard",
        conceptIds: ["workflow-check"],
      },
      {
        title: "保護ルールは統合条件を強制する",
        lead: "mainへの直接pushを制限し、PR、承認数、必須チェック、最新mainとの同期などを要求できます。Actionsは検査を実行し、保護ルールは結果を統合条件として使います。管理者の例外も最小限にします。",
        points: ["自動検査と承認を組み合わせる", "重要ブランチへの直送を防ぐ", "厳しさはチーム規模とリスクに合わせる"],
        talk: [
          { speaker: "beginner", text: "管理者なら急ぎの修正を直接入れる方が速いですよね？" },
          { speaker: "engineer", text: "緊急手順を定義し、例外も記録と事後確認が残る形にします。" },
        ],
        diagram: "git-actions",
        storyBeat: "resolution",
        objectiveId: "automation-guard",
        conceptIds: ["branch-protection"],
      },
    ],
    questions: [
      {
        id: "automation-guard-roles",
        slide: 2,
        prompt: "自動検査と保護ルールの関係として適切なものを選んでください。",
        kind: "choice",
        options: ["検査が結果を作り、保護ルールが統合条件に使う", "検査と保護ルールがファイルを手動で直接編集する", "保護ルール自身が必要なテストコードをすべて書く", "自動検査の結果だけでレビュー承認者を決める"],
        answer: "検査が結果を作り、保護ルールが統合条件に使う",
        explain: "Actionsなどがチェックを実行し、保護ルールが通過をmainへの統合条件として強制します。",
        hints: ["実行する役割と門番の役割を分けます。", "一方の結果をもう一方が利用します。", "検査から統合条件へ流れる選択肢です。"],
        objectiveId: "automation-guard",
        conceptIds: ["github-actions", "branch-protection"],
        gitInitialState: { files: { ".github/workflows/test.yml": "name: test" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "automation-guard-format",
        slide: 1,
        prompt: "失敗したチェックを調べるとき、再実行より先に読むものを漢字2文字で入力してください。",
        kind: "input",
        answer: "原因",
        explain: "失敗したjobと最初の有意味なエラーから、原因を切り分けます。",
        hints: ["赤い印だけで判断しません。", "最初の有意味なエラーを読みます。", "なぜ失敗したかを表す漢字2文字です。"],
        objectiveId: "automation-guard",
        conceptIds: ["workflow-check"],
        gitInitialState: { files: { ".github/workflows/test.yml": "name: test" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "automation-guard-workflow",
        slide: 0,
        prompt: "作成済みの.github/workflows/test.ymlを選び、「注文テストの自動検査を追加」と履歴へ記録してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: `git add .github/workflows/test.yml
git commit -m "注文テストの自動検査を追加"`,
        explain: "workflow定義もコードとしてレビュー可能な履歴へ残します。実GitHub Actionsは起動しません。",
        hints: ["最初に定義ファイルだけを次の記録へ選びます。", "次に目的が分かる説明で確定します。", "隠しディレクトリから始まる完全なパスを使います。"],
        objectiveId: "automation-guard",
        conceptIds: ["github-actions", "workflow-check"],
        gitInitialState: { files: { ".github/workflows/test.yml": "name: test\non: pull_request\njobs: {}" }, branch: "main" },
        gitAssertions: [{ kind: "staged", path: ".github/workflows/test.yml" }, { kind: "commit-count", count: 1 }],
      },
    ],
  },
];
