import type { Lesson } from "@/lib/course/types";

export const githubStart: Lesson[] = [
  {
    id: "github-repository-basics",
    track: "github",
    level: "start",
    chapter: "github-repository",
    order: 1,
    title: "GitとGitHubを分けて、記録を始める",
    summary: "手元の履歴管理と共有サービスの違い、initとstatus",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "変更ファイルをチャットで送り合い、最新版が分からなくなった",
      outcome: "手元にリポジトリを作り、変更の所在を確認できる",
    },
    objectives: [
      { id: "repo-role", label: "GitとGitHubの役割を分けて説明し、リポジトリを初期化できる", conceptIds: ["git-role", "git-init", "git-status"] },
    ],
    slides: [
      {
        title: "Gitは記録係、GitHubは共有場所",
        lead: "注文管理チームでは、店員画面の変更を各自のPCで進めます。GitはそのPC上で差分と履歴を記録する道具、GitHubは記録を置いて相談するサービスです。Gitだけなら通信なしで使えます。この講座のGitHub操作もすべて模擬環境で、実サービスへの接続や公開は行いません。",
        points: ["Gitはローカルでも動く", "GitHubはリポジトリ共有やレビューを支える", "この教材は通信しない安全なシミュレーター"],
        talk: [
          { speaker: "beginner", text: "Gitを使うと、注文データが自動でGitHubへ公開されますか？" },
          { speaker: "engineer", text: "いいえ。Gitの記録はまず手元だけです。共有操作をして初めて外部の置き場所が関係します。" },
        ],
        diagram: "git-repository",
        storyBeat: "problem",
        storyContext: "最新版が散らばった注文管理アプリ",
        objectiveId: "repo-role",
        conceptIds: ["git-role"],
      },
      {
        title: "initで記録用の箱を作る",
        lead: "orders-appフォルダーをGitで管理するには、最初に初期化します。作られる.gitは履歴や設定の保管庫です。商品画像やソースそのものを別の場所へ移す操作ではありません。",
        points: ["初期化は通常1リポジトリにつき一度", ".gitを消すと履歴管理情報を失う", "既存ファイルはまだコミットされない"],
        talk: [
          { speaker: "beginner", text: "初期化した瞬間に、今ある注文画面が保存版になりますか？" },
          { speaker: "engineer", text: "箱ができるだけです。記録する変更は、このあと選んでコミットします。" },
        ],
        diagram: "git-repository",
        code: `orders-app/
├── .git/       # Gitの管理情報
├── app.js
└── orders.json`,
        storyBeat: "trace",
        objectiveId: "repo-role",
        conceptIds: ["git-init"],
      },
      {
        title: "statusは現在地を読む窓",
        lead: "初期化の後は状態を確認します。statusは、現在のブランチ、未追跡、変更済み、ステージ済みを分類します。何かを保存したり送信したりせず、状況を読むための安全な操作です。",
        points: ["untrackedはまだ追跡対象として選ばれていない", "modifiedは追跡中ファイルが変わった", "作業前後にstatusを見ると迷子になりにくい"],
        talk: [
          { speaker: "beginner", text: "赤いファイル名が出たら、失敗という意味ですか？" },
          { speaker: "engineer", text: "色は状態の区別です。エラーと決めつけず、見出しと一緒に読みます。" },
        ],
        diagram: "git-repository",
        code: `$ git status
On branch main
Untracked files:
  orders.json`,
        storyBeat: "resolution",
        objectiveId: "repo-role",
        conceptIds: ["git-status"],
      },
    ],
    questions: [
      {
        id: "repo-basics-role",
        slide: 0,
        prompt: "手元のPCだけで差分と履歴を管理する役割を持つものを選んでください。",
        kind: "choice",
        options: ["Git（手元の履歴管理）", "GitHub（共有とレビュー）", "注文API（データ通信）", "ブラウザ（画面表示）"],
        answer: "Git（手元の履歴管理）",
        explain: "Gitはローカルで履歴を扱う道具です。GitHubは共有やレビューを提供する別のサービスです。",
        hints: ["通信しなくても使える側を考えます。", "Webサービスではなく、履歴管理の道具です。", "名前が短い方の道具です。"],
        objectiveId: "repo-role",
        conceptIds: ["git-role"],
        gitInitialState: { files: { "app.js": "console.log('orders');" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "repo-basics-term",
        slide: 1,
        prompt: "リポジトリの管理情報を置く隠しディレクトリ名を入力してください。",
        kind: "input",
        answer: ".git",
        explain: "初期化すると.gitディレクトリに履歴や設定が保存されます。",
        hints: ["通常は画面に表示されない名前です。", "先頭にドットが付きます。", "履歴管理ツール名をドットの後へ続けます。"],
        objectiveId: "repo-role",
        conceptIds: ["git-init"],
        gitInitialState: { files: { "orders.json": "[]" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "repo-basics-init",
        slide: 2,
        prompt: "orders-appをmainブランチで履歴管理できる状態にしてください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: "git init -b main",
        explain: "初期化時に既定ブランチ名も指定すると、チームで開始地点を揃えられます。",
        hints: ["新しい履歴の箱を作る操作です。", "初期化するサブコマンドを使います。", "ブランチ名を指定する短いオプションを添えます。"],
        objectiveId: "repo-role",
        conceptIds: ["git-init"],
        gitInitialState: { files: { "app.js": "console.log('orders');" }, initialized: false },
        gitAssertions: [{ kind: "initialized" }, { kind: "branch", name: "main" }],
      },
    ],
  },
  {
    id: "github-commit-basics",
    track: "github",
    level: "start",
    chapter: "github-commit",
    order: 2,
    title: "変更を選んでコミットする",
    summary: "status、add、commitを荷造りの順で理解する",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "送料修正と調査メモが同じ作業フォルダーに混ざった",
      outcome: "必要な変更だけを一つの履歴として記録できる",
    },
    objectives: [
      { id: "commit-flow", label: "作業ツリー、ステージ、コミットの流れを操作できる", conceptIds: ["git-status", "git-add", "git-commit"] },
    ],
    slides: [
      {
        title: "statusで荷物を仕分ける",
        lead: "送料計算のapp.jsと個人メモnotes.txtが変更されています。全部を一度に記録せず、まずstatusで差分の候補を確認します。作業ツリーは机、ステージは今回の箱、コミットは封をした荷物です。",
        points: ["作業ツリーには編集中の変更がある", "ステージには次回記録する変更だけを置く", "コミットはステージの内容を履歴にする"],
        talk: [
          { speaker: "beginner", text: "保存したファイルは、全部すぐ履歴になりますか？" },
          { speaker: "engineer", text: "ファイル保存とGitの記録は別です。今回の記録に入れるものを選びます。" },
        ],
        diagram: "git-staging",
        storyBeat: "problem",
        objectiveId: "commit-flow",
        conceptIds: ["git-status"],
      },
      {
        title: "addは次の記録へ載せる",
        lead: "今回は送料修正だけを届けたいのでapp.jsをステージします。addはGitHubへ送る操作でも、確定操作でもありません。次のコミットに含める内容を選ぶ操作です。",
        points: ["ファイル単位でも選べる", "追加後にさらに編集すると、追加済みと未追加の差分が分かれる", "迷ったら再びstatusを見る"],
        talk: [
          { speaker: "beginner", text: "addしたら、もう修正できませんか？" },
          { speaker: "engineer", text: "修正できます。コミット前なら、箱の中身を確認して選び直せます。" },
        ],
        diagram: "git-staging",
        code: `作業ツリー ── add ──> ステージ ── commit ──> 履歴`,
        storyBeat: "trace",
        objectiveId: "commit-flow",
        conceptIds: ["git-add"],
      },
      {
        title: "コミットは理由が伝わる一単位",
        lead: "コミットメッセージには、何をしたかが後から分かる短い説明を書きます。「修正」だけではなく「送料の端数計算を修正」のように目的を残します。一つのコミットに無関係な作業を詰め込まないこともレビューを助けます。",
        points: ["履歴はチームへの説明になる", "小さく関連した変更をまとめる", "記録後はlogで流れを確認できる"],
        talk: [
          { speaker: "beginner", text: "メッセージは自分だけ分かれば十分ですか？" },
          { speaker: "engineer", text: "未来の自分と仲間が読む前提で、変更の目的を残しましょう。" },
        ],
        diagram: "git-history",
        storyBeat: "resolution",
        objectiveId: "commit-flow",
        conceptIds: ["git-commit"],
      },
    ],
    questions: [
      {
        id: "commit-basics-stage",
        slide: 0,
        prompt: "次のコミットへ含める変更を一時的に選ぶ場所を選んでください。",
        kind: "choice",
        options: ["ステージ", "リモート", "Issue", "Actions"],
        answer: "ステージ",
        explain: "ステージは次回のコミットに含める内容を組み立てる場所です。",
        hints: ["作業机と確定済み履歴の間です。", "発送前の箱に相当します。", "カタカナ4文字の場所です。"],
        objectiveId: "commit-flow",
        conceptIds: ["git-add"],
        gitInitialState: { files: { "app.js": "const fee = 500;" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "commit-basics-message",
        slide: 2,
        prompt: "確定済みの履歴を新しい順で確認するサブコマンド名を入力してください。",
        kind: "input",
        answer: "log",
        explain: "履歴確認ではコミットの識別子、作者、日時、メッセージをたどれます。",
        hints: ["状態一覧とは別の操作です。", "記録を読む英単語です。", "3文字のサブコマンドです。"],
        objectiveId: "commit-flow",
        conceptIds: ["git-commit"],
        gitInitialState: { files: { "app.js": "const fee = 500;" }, branch: "main" },
        gitAssertions: [{ kind: "commit-count", count: 0 }],
      },
      {
        id: "commit-basics-record",
        slide: 1,
        prompt: "注文送料を直したapp.jsだけを選び、「送料計算を修正」という説明で履歴へ記録してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: `git add app.js
git commit -m "送料計算を修正"`,
        explain: "対象をステージしてからコミットすると、notes.txtを混ぜずに一つの意図を記録できます。",
        hints: ["最初に今回の箱へ対象ファイルだけ入れます。", "次に履歴へ確定する操作へ進みます。", "説明文はメッセージ用オプションへ渡します。"],
        objectiveId: "commit-flow",
        conceptIds: ["git-add", "git-commit"],
        gitInitialState: { files: { "app.js": "const fee = 550;", "notes.txt": "調査中" }, branch: "main" },
        gitAssertions: [{ kind: "commit-count", count: 1 }],
      },
    ],
  },
  {
    id: "github-branch-basics",
    track: "github",
    level: "basic",
    chapter: "github-branch",
    order: 3,
    title: "ブランチで安全な作業線を作る",
    summary: "branch、switch、mergeで担当作業を分離する",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "本番向けmain上で未完成の検索機能を編集してしまった",
      outcome: "機能ごとの枝で作業し、完成後に統合できる",
    },
    objectives: [
      { id: "branch-flow", label: "作業ブランチを作成して切り替えられる", conceptIds: ["git-branch", "git-switch", "git-merge"] },
    ],
    slides: [
      {
        title: "ブランチは履歴の分かれ道",
        lead: "注文検索はまだ試作中です。mainを安定した幹として残し、feature/searchという枝で作業します。ブランチはフォルダーの複製ではなく、コミットを指す軽い目印です。",
        points: ["mainと作業中の変更を分ける", "ブランチ名は目的が伝わるようにする", "現在地を確認してから編集する"],
        talk: [
          { speaker: "beginner", text: "枝を作るとプロジェクト容量が2倍ですか？" },
          { speaker: "engineer", text: "丸ごとコピーではありません。履歴上の位置を示す目印として考えます。" },
        ],
        diagram: "git-branch",
        storyBeat: "problem",
        objectiveId: "branch-flow",
        conceptIds: ["git-branch"],
      },
      {
        title: "switchで作業場所を移る",
        lead: "枝を作っただけでは現在地が移らない場合があります。切り替えると、作業ツリーがその枝の状態に合わせて更新されます。未コミット変更があると安全のため切り替えを止められることがあります。",
        points: ["作成と切り替えを同時にも行える", "切り替え前にstatusで未記録変更を見る", "現在の枝には印が付く"],
        talk: [
          { speaker: "beginner", text: "画面上のファイルが変わるのは、削除されたからですか？" },
          { speaker: "engineer", text: "選んだ履歴の状態へ作業ツリーを合わせています。ブランチを戻せば対応する内容になります。" },
        ],
        diagram: "git-branch",
        storyBeat: "trace",
        objectiveId: "branch-flow",
        conceptIds: ["git-switch"],
      },
      {
        title: "mergeで枝の成果を統合する",
        lead: "検索機能が完成したら、統合先のmainへ移ってから作業枝をマージします。「どこへ何を入れるか」は現在地で決まるため、先にブランチを確かめます。",
        points: ["統合先へ先に切り替える", "衝突がなければ履歴が一つにつながる", "作業枝を消すのは統合確認後"],
        talk: [
          { speaker: "beginner", text: "作業枝にいるままmainを指定すれば、mainへ入りますか？" },
          { speaker: "engineer", text: "逆方向になります。先に受け取り側へ移る、と覚えましょう。" },
        ],
        diagram: "git-branch",
        storyBeat: "resolution",
        objectiveId: "branch-flow",
        conceptIds: ["git-merge"],
      },
    ],
    questions: [
      {
        id: "branch-basics-model",
        slide: 0,
        prompt: "ブランチの説明として最も適切なものを選んでください。",
        kind: "choice",
        options: ["コミットを指す移動可能な目印", "プロジェクト全体の圧縮ファイル", "GitHubの利用者アカウント", "未追跡ファイルの一覧"],
        answer: "コミットを指す移動可能な目印",
        explain: "ブランチは履歴上のコミットを指し、記録が増えると先へ動く軽い参照です。",
        hints: ["ファイル一式のコピーではありません。", "履歴のどこにいるかを表します。", "コミットとの関係を見る選択肢です。"],
        objectiveId: "branch-flow",
        conceptIds: ["git-branch"],
        gitInitialState: { files: { "app.js": "renderOrders();" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "branch-basics-current",
        slide: 2,
        prompt: "統合操作の前に移動しておくべき側を、役割を表す4文字で入力してください。",
        kind: "input",
        answer: "統合先",
        explain: "マージは現在のブランチへ指定ブランチを取り込むため、受け取り側へ先に移ります。",
        hints: ["成果を受け取る側です。", "作業枝ではない方へ移ります。", "「先」は行き先を表します。"],
        objectiveId: "branch-flow",
        conceptIds: ["git-merge"],
        gitInitialState: { files: { "app.js": "renderOrders();" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "branch-basics-create",
        slide: 1,
        prompt: "注文検索を開発するため、現在のmainからfeature/searchを作り、そのブランチへ移動してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: "git switch -c feature/search",
        explain: "作成オプション付きの切り替えなら、現在地から新しい枝を作って移動できます。",
        hints: ["ブランチを移動する操作を使います。", "まだ存在しないため作成も必要です。", "作成を表す短いオプションを添えます。"],
        objectiveId: "branch-flow",
        conceptIds: ["git-branch", "git-switch"],
        gitInitialState: { files: { "app.js": "renderOrders();" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "feature/search" }],
      },
    ],
  },
  {
    id: "github-remote-basics",
    track: "github",
    level: "basic",
    chapter: "github-remote",
    order: 4,
    title: "remoteとpushで履歴を共有する",
    summary: "ローカルとリモートを分け、安全に初回共有する",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "自分のPCでは検索機能が完成したが、仲間から見えない",
      outcome: "共有先を登録し、作業ブランチの履歴を届けられる",
    },
    objectives: [
      { id: "remote-flow", label: "リモートを登録し、ブランチを共有できる", conceptIds: ["git-remote", "git-push", "git-upstream"] },
    ],
    slides: [
      {
        title: "remoteは共有先への名札",
        lead: "手元のリポジトリと共有側のリポジトリは別物です。originはURLへ付ける慣例的な短い名前で、魔法のサーバー名ではありません。この教材ではURLも模擬値で、GitHubへの実通信は発生しません。",
        points: ["remoteは共有先URLの別名", "複数の共有先も登録できる", "登録だけでは履歴を送らない"],
        talk: [
          { speaker: "beginner", text: "originを付けたら自動同期が始まりますか？" },
          { speaker: "engineer", text: "いいえ。住所を登録しただけです。送受信は別の操作です。" },
        ],
        diagram: "git-remote",
        storyBeat: "problem",
        objectiveId: "remote-flow",
        conceptIds: ["git-remote"],
      },
      {
        title: "pushは手元の履歴を届ける",
        lead: "作業ブランチのコミットを共有側へ送るのがpushです。ファイルを一枚ずつアップロードするのではなく、Gitの履歴を共有します。未コミットの編集は送られません。",
        points: ["コミット済み履歴が対象", "送るブランチを意識する", "拒否されたら先に相手側の更新を確認する"],
        talk: [
          { speaker: "beginner", text: "保存したばかりの未コミット変更も仲間に見えますか？" },
          { speaker: "engineer", text: "pushされるのは履歴です。まずコミットが必要です。" },
        ],
        diagram: "git-remote",
        storyBeat: "trace",
        objectiveId: "remote-flow",
        conceptIds: ["git-push"],
      },
      {
        title: "upstreamで次回の行き先を覚える",
        lead: "初回pushで追跡先を設定すると、次回から送り先とブランチを省略しやすくなります。ローカルfeature/searchと共有側の同名ブランチを対応付けるイメージです。",
        points: ["初回は対応関係を明示する", "以後の省略形でも現在ブランチを確認する", "push成功とPR作成は別"],
        talk: [
          { speaker: "beginner", text: "pushした時点でmainへ統合されますか？" },
          { speaker: "engineer", text: "共有側に枝ができるだけです。統合の相談はPull Requestで行います。" },
        ],
        diagram: "git-remote",
        storyBeat: "resolution",
        objectiveId: "remote-flow",
        conceptIds: ["git-upstream"],
      },
    ],
    questions: [
      {
        id: "remote-basics-origin",
        slide: 0,
        prompt: "originが表すものとして適切な説明を選んでください。",
        kind: "choice",
        options: ["リモートURLに付けた短い名前", "GitHub社だけにあるサーバー名", "現在作業中のブランチの名前", "履歴で最初に作ったコミット名"],
        answer: "リモートURLに付けた短い名前",
        explain: "originはよく使われる慣例名で、登録した共有先URLを参照します。",
        hints: ["固有のサービス名ではありません。", "長い住所を扱いやすくします。", "URLとの関係がある選択肢です。"],
        objectiveId: "remote-flow",
        conceptIds: ["git-remote"],
        gitInitialState: { files: { "app.js": "renderOrders();" }, branch: "feature/search" },
        gitAssertions: [{ kind: "branch", name: "feature/search" }],
      },
      {
        id: "remote-basics-unsent",
        slide: 1,
        prompt: "送信対象にならない、作業ツリーにだけある変更状態を英字で入力してください。",
        kind: "input",
        answer: "uncommitted",
        explain: "共有されるのはコミットされた履歴で、未コミット変更は手元に残ります。",
        hints: ["まだ履歴として確定していません。", "英語では否定の接頭辞が付きます。", "確定済みを表す語の前にunを付けます。"],
        objectiveId: "remote-flow",
        conceptIds: ["git-push"],
        gitInitialState: { files: { "app.js": "renderOrders();" }, branch: "feature/search" },
        gitAssertions: [{ kind: "branch", name: "feature/search" }],
      },
      {
        id: "remote-basics-share",
        slide: 2,
        prompt: "模擬共有先をoriginとして登録し、現在のfeature/searchを追跡先付きで初回共有してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: `git remote add origin https://example.invalid/team/orders-app.git
git push -u origin feature/search`,
        explain: "共有先の名札を登録し、初回pushで上流ブランチとの対応も設定します。模擬URLなので実通信はありません。",
        hints: ["最初に短い名前と模擬URLを対応付けます。", "次に履歴を送る操作を使います。", "追跡先を覚える短いオプションを加えます。"],
        objectiveId: "remote-flow",
        conceptIds: ["git-remote", "git-push", "git-upstream"],
        gitInitialState: { files: { "app.js": "renderOrders();" }, branch: "feature/search" },
        gitAssertions: [{ kind: "remote", name: "origin" }, { kind: "pushed", branch: "feature/search" }],
      },
    ],
  },
  {
    id: "github-pr-basics",
    track: "github",
    level: "middle",
    chapter: "github-pr",
    order: 5,
    title: "ghでPull Requestを作る",
    summary: "認証状態を確かめ、変更提案をレビューへ渡す",
    minutes: 20,
    story: {
      project: "注文管理アプリ",
      incident: "検索機能のブランチは共有したが、誰も変更目的を把握していない",
      outcome: "CLIからPRを作り、mainへの統合を相談できる",
    },
    objectives: [
      { id: "pr-flow", label: "ghの認証状態を確認し、PRを作成できる", conceptIds: ["gh-auth", "gh-pr-create", "git-pr"] },
    ],
    slides: [
      {
        title: "ghはGitHub操作用の別CLI",
        lead: "gitが履歴を扱うのに対し、ghはGitHub上のPRやIssueを操作するCLIです。利用前には認証状態を確認します。この教材のghは模擬実装で、アカウントへのログインも外部接続も行いません。",
        points: ["gitとghは役割が違う", "認証状態を先に確認する", "教材内の結果はすべてシミュレーション"],
        talk: [
          { speaker: "beginner", text: "gitでコミットできれば、ghも自動でログイン済みですか？" },
          { speaker: "engineer", text: "別の道具なので認証も別です。操作前に状態を確認します。" },
        ],
        diagram: "git-pr",
        code: `gh auth status
# 教材では模擬認証の状態を表示`,
        storyBeat: "problem",
        objectiveId: "pr-flow",
        conceptIds: ["gh-auth"],
      },
      {
        title: "PRは変更を入れてよいか相談する場",
        lead: "Pull Requestはfeature/searchからmainへ変更を取り込む提案です。baseは受け取り側、headは変更を持つ側です。タイトルには目的、本文には理由や確認方法を書きます。",
        points: ["baseとheadの向きを確かめる", "変更の背景とテスト方法を書く", "pushだけではPRは作られない"],
        talk: [
          { speaker: "beginner", text: "名前にPullとあるので、仲間の変更を取得する操作ですか？" },
          { speaker: "engineer", text: "ここでは統合を依頼する提案です。git pullとは別物です。" },
        ],
        diagram: "git-pr",
        storyBeat: "trace",
        objectiveId: "pr-flow",
        conceptIds: ["git-pr"],
      },
      {
        title: "pr createで提案を形にする",
        lead: "作業枝をpushしたら、統合先、作業元、題名、説明を指定してPRを作ります。作成後に表示される番号やURLはレビューの入口です。模擬環境では架空のPRだけが作られます。",
        points: ["作成前に差分とブランチを確認", "レビューしやすい単位にする", "PR作成は即マージではない"],
        talk: [
          { speaker: "beginner", text: "PRを作ると、検索機能はすぐmainに入りますか？" },
          { speaker: "engineer", text: "まだ提案です。確認と承認を経て、別の統合操作を行います。" },
        ],
        diagram: "git-pr",
        code: `gh pr create --base main --head feature/search`,
        storyBeat: "resolution",
        objectiveId: "pr-flow",
        conceptIds: ["gh-pr-create"],
      },
    ],
    questions: [
      {
        id: "pr-basics-tools",
        slide: 0,
        prompt: "PRやIssueなど共有サービス上の機能を操作するCLIを選んでください。",
        kind: "choice",
        options: ["gh", "git", "node", "npm"],
        answer: "gh",
        explain: "ghはGitHub CLIで、PRやIssueなどサービス上の機能を扱います。",
        hints: ["履歴管理そのものとは別の道具です。", "GitHubの頭文字に近い名前です。", "2文字のCLIです。"],
        objectiveId: "pr-flow",
        conceptIds: ["gh-auth"],
        gitInitialState: { files: { "search.js": "export const search = () => [];" }, branch: "feature/search", remote: "origin" },
        gitAssertions: [{ kind: "branch", name: "feature/search" }],
      },
      {
        id: "pr-basics-base",
        slide: 1,
        prompt: "PRで変更を受け取る側を表す英単語を入力してください。",
        kind: "input",
        answer: "base",
        explain: "baseは統合先、headは変更を持つ作業元を表します。",
        hints: ["作業枝ではなく土台側です。", "4文字の英単語です。", "土台という意味の語です。"],
        objectiveId: "pr-flow",
        conceptIds: ["git-pr"],
        gitInitialState: { files: { "search.js": "export const search = () => [];" }, branch: "feature/search", remote: "origin" },
        gitAssertions: [{ kind: "branch", name: "feature/search" }],
      },
      {
        id: "pr-basics-create",
        slide: 2,
        prompt: "feature/searchからmainへ、題名「注文検索を追加」、本文「一覧を絞り込めます」の模擬PRを作成してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "gh auth status\n",
        answer: `gh auth status
gh pr create --base main --head feature/search --title "注文検索を追加" --body "一覧を絞り込めます"`,
        explain: "認証状態を確認してから、統合先と作業元を明示して変更提案を作ります。実サービスには接続しません。",
        hints: ["最初にCLIの認証状態を確かめます。", "次にPRを新規作成するサブコマンドです。", "受け取り側と作業側を逆にしないよう指定します。"],
        objectiveId: "pr-flow",
        conceptIds: ["gh-auth", "gh-pr-create"],
        gitInitialState: { files: { "search.js": "export const search = () => [];" }, branch: "feature/search", remote: "origin" },
        gitAssertions: [{ kind: "pr-open", base: "main", head: "feature/search" }],
      },
    ],
  },
  {
    id: "github-conflict-basics",
    track: "github",
    level: "middle",
    chapter: "github-conflict",
    order: 6,
    title: "コンフリクトを読んで解決する",
    summary: "衝突印を手掛かりに、意図を統合して記録する",
    minutes: 20,
    story: {
      project: "注文管理アプリ",
      incident: "二人が同じ送料表示を別々に変更し、自動統合できなくなった",
      outcome: "両方の意図を確認し、正しい一つの内容へ直せる",
    },
    objectives: [
      { id: "conflict-flow", label: "競合箇所を読み、解決済みとして記録できる", conceptIds: ["git-conflict", "git-markers", "git-resolve"] },
    ],
    slides: [
      {
        title: "競合は失敗ではなく判断待ち",
        lead: "同じ行付近を二つの枝が変えると、Gitはどちらを採用すべきか決められません。そこで処理を止め、人に意図の判断を求めます。注文送料なら、片方を機械的に消す前に仕様を確認します。",
        points: ["競合は変更を失ったという意味ではない", "statusで対象ファイルを特定する", "誰の変更かより、完成形の仕様で決める"],
        talk: [
          { speaker: "beginner", text: "赤い表示なら、片方の変更は壊れていますか？" },
          { speaker: "engineer", text: "両方とも正しい可能性があります。Gitが完成形を判断できないだけです。" },
        ],
        diagram: "git-conflict",
        storyBeat: "problem",
        objectiveId: "conflict-flow",
        conceptIds: ["git-conflict"],
      },
      {
        title: "衝突マーカーの内側を読む",
        lead: "ファイルには現在側、区切り、取り込み側を示す印が入ります。印を残したままでは解決ではありません。二つの内容と要件を比べ、最終的に必要なコードだけへ編集します。",
        points: ["上側と下側の出所を確認", "片方を選ぶだけでなく組み合わせる場合もある", "マーカー行をすべて除く"],
        talk: [
          { speaker: "beginner", text: "上側を毎回残せば安全ですか？" },
          { speaker: "engineer", text: "位置だけでは決められません。注文仕様に合う完成形を作ります。" },
        ],
        diagram: "git-conflict",
        code: `<<<<<<< HEAD
const fee = 500;
=======
const fee = calculateFee(order);
>>>>>>> feature/fee`,
        storyBeat: "trace",
        objectiveId: "conflict-flow",
        conceptIds: ["git-markers"],
      },
      {
        title: "編集、add、commitで解決を記録する",
        lead: "正しい内容へ編集しただけでは、Gitは判断完了を知りません。対象を再度ステージし、統合コミットを作ります。その前に差分とテストを確認し、マーカーが残っていないか検索します。",
        points: ["編集後のaddが解決済みの合図", "注文計算のテストを実行", "最後に統合結果をコミット"],
        talk: [
          { speaker: "beginner", text: "保存したらマージが自動再開しますか？" },
          { speaker: "engineer", text: "Gitへ解決済みと伝えるため、ステージして記録まで完了させます。" },
        ],
        diagram: "git-conflict",
        storyBeat: "resolution",
        objectiveId: "conflict-flow",
        conceptIds: ["git-resolve"],
      },
    ],
    questions: [
      {
        id: "conflict-basics-meaning",
        slide: 0,
        prompt: "競合が起きた状態の説明として適切なものを選んでください。",
        kind: "choice",
        options: ["Gitが完成形を自動判断できず待っている", "すべてのコミットと履歴が消えている", "GitHubへのログイン認証だけが切れている", "相手側の変更だけが必ず誤りになっている"],
        answer: "Gitが完成形を自動判断できず待っている",
        explain: "競合では候補が残っており、人が仕様に沿った完成形を決めます。",
        hints: ["履歴が消えたわけではありません。", "二つの変更候補があります。", "人の判断を必要とする選択肢です。"],
        objectiveId: "conflict-flow",
        conceptIds: ["git-conflict"],
        gitInitialState: { files: { "fee.js": "const fee = 500;" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "conflict-basics-signal",
        slide: 1,
        prompt: "競合箇所で、現在側と取り込み側の境目を示すマーカーを入力してください。",
        kind: "input",
        answer: "=======",
        explain: "7個のイコール記号が、競合した二つの内容の境目を示します。",
        hints: ["上下の内容を分ける中央の行です。", "同じ記号が並びます。", "イコール記号を7個入力します。"],
        objectiveId: "conflict-flow",
        conceptIds: ["git-markers"],
        gitInitialState: { files: { "fee.js": "const fee = 500;" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "conflict-basics-resolve",
        slide: 2,
        prompt: "注文送料のfee.jsは仕様確認済みの内容へ編集されています。解決済みとして選び、「送料競合を解決」と記録してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: `git add fee.js
git commit -m "送料競合を解決"`,
        explain: "編集済みファイルをステージし、統合結果をコミットして競合解決を履歴へ残します。",
        hints: ["まず対象ファイルを今回の記録へ含めます。", "次に確定済み履歴を作ります。", "解決理由をメッセージとして渡します。"],
        objectiveId: "conflict-flow",
        conceptIds: ["git-resolve"],
        gitInitialState: { files: { "fee.js": "const fee = calculateFee(order);" }, branch: "main" },
        gitAssertions: [{ kind: "commit-count", count: 1 }],
      },
    ],
  },
  {
    id: "github-automation-basics",
    track: "github",
    level: "middle",
    chapter: "github-automation",
    order: 7,
    title: "Issueで共同作業を整理する",
    summary: "課題、担当、完了条件を共有して変更の入口を作る",
    minutes: 18,
    story: {
      project: "注文管理アプリ",
      incident: "チャットの「検索を直す」が流れ、担当と完了条件が曖昧になった",
      outcome: "Issueへ背景と完了条件を残し、ブランチやPRと結び付けられる",
    },
    objectives: [
      { id: "issue-flow", label: "レビュー可能なIssueの要素を説明できる", conceptIds: ["github-issue", "issue-scope", "issue-link"] },
    ],
    slides: [
      {
        title: "Issueは作業の共通メモ",
        lead: "Issueには「何が困っているか」「どうなれば完了か」を残します。単なる命令一覧ではなく、注文検索が遅い状況や再現手順を共有する場所です。この教材のIssue作成も模擬で、実GitHubへは送信しません。",
        points: ["背景と利用者への影響を書く", "一つの判断可能な範囲へ絞る", "秘密情報や実注文データは載せない"],
        talk: [
          { speaker: "beginner", text: "題名を『修正』だけにして、詳細は口頭で伝えてもよいですか？" },
          { speaker: "engineer", text: "後から参加する人も判断できるよう、背景と完了条件をIssueへ残します。" },
        ],
        diagram: "git-actions",
        storyBeat: "problem",
        objectiveId: "issue-flow",
        conceptIds: ["github-issue"],
      },
      {
        title: "完了条件は確認できる言葉にする",
        lead: "「いい感じに速くする」では終わりを判定できません。「100件の注文を状態で絞り込める」「既存テストが通る」のように観察可能な条件にします。担当者やラベルは整理を助けますが、本文の代わりではありません。",
        points: ["再現手順を書く", "期待結果と現在結果を分ける", "チェック可能な完了条件にする"],
        talk: [
          { speaker: "beginner", text: "実装方法まで細かく固定した方が迷いませんか？" },
          { speaker: "engineer", text: "必要な制約は書きますが、まず解決すべき問題と完了条件を明確にします。" },
        ],
        diagram: "git-actions",
        storyBeat: "trace",
        objectiveId: "issue-flow",
        conceptIds: ["issue-scope"],
      },
      {
        title: "Issue、ブランチ、PRを一本の物語にする",
        lead: "Issue番号をブランチ名やPR本文に記すと、問題から変更理由までたどれます。PRで完了条件を確認し、統合後にIssueを閉じます。閉じることより、検証済みであることが重要です。",
        points: ["Issueはなぜ、PRはどう変えたか", "関連番号で追跡可能にする", "完了条件をレビューで再確認する"],
        talk: [
          { speaker: "beginner", text: "コードが書けたら、Issueは先に閉じてよいですか？" },
          { speaker: "engineer", text: "統合と確認まで終わったか、定義した完了条件で判断しましょう。" },
        ],
        diagram: "git-actions",
        storyBeat: "resolution",
        objectiveId: "issue-flow",
        conceptIds: ["issue-link"],
      },
    ],
    questions: [
      {
        id: "automation-basics-issue",
        slide: 0,
        prompt: "共同作業の課題を判断可能にする情報として、最も重要な組み合わせを選んでください。",
        kind: "choice",
        options: ["背景と完了条件", "担当者名だけ", "絵文字だけ", "実注文の個人情報"],
        answer: "背景と完了条件",
        explain: "なぜ必要かと、何をもって終わりとするかがあれば、担当外の人も判断できます。",
        hints: ["名前だけでは目的が分かりません。", "開始理由と終了判断を考えます。", "二つの情報を含む選択肢です。"],
        objectiveId: "issue-flow",
        conceptIds: ["github-issue"],
        gitInitialState: { files: { "README.md": "# Orders" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "automation-basics-link",
        slide: 1,
        prompt: "完了条件は、あとから結果を何できる言葉で書きますか。漢字2文字で入力してください。",
        kind: "input",
        answer: "確認",
        explain: "完了条件を確認できる言葉にすると、作業が終わったかを誰でも判断できます。",
        hints: ["曖昧な感想では判断できません。", "結果を後から確かめられる表現にします。", "確かめることを表す漢字2文字です。"],
        objectiveId: "issue-flow",
        conceptIds: ["issue-scope"],
        gitInitialState: { files: { "README.md": "# Orders" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "main" }],
      },
      {
        id: "automation-basics-branch",
        slide: 2,
        prompt: "模擬Issue 42の注文検索改善に着手するため、issue/42-searchという作業ブランチを作って移動してください。",
        kind: "git",
        runtime: "git",
        cwd: "orders-app",
        starter: "",
        answer: "git switch -c issue/42-search",
        explain: "Issue番号を含むブランチ名にすると、課題と作業履歴の関係をたどりやすくなります。",
        hints: ["現在のmainから新しい枝を作ります。", "作成と移動を一度に行えます。", "切り替え操作へ作成用の短いオプションを付けます。"],
        objectiveId: "issue-flow",
        conceptIds: ["issue-link", "git-branch"],
        gitInitialState: { files: { "README.md": "# Orders" }, branch: "main" },
        gitAssertions: [{ kind: "branch", name: "issue/42-search" }],
      },
    ],
  },
];
