import type { Lesson } from "@/lib/course/types";

const orderSchema = `
CREATE TABLE customers (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  area TEXT NOT NULL
);
CREATE TABLE orders (
  id INTEGER PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  item TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price INTEGER NOT NULL,
  status TEXT,
  ordered_at TEXT NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);`.trim();

const orderSeed = `
INSERT INTO customers (id, name, area) VALUES
  (1, '田中', '東京'),
  (2, '佐藤', '大阪'),
  (3, '鈴木', '東京');
INSERT INTO orders (id, customer_id, item, quantity, unit_price, status, ordered_at) VALUES
  (101, 1, 'コーヒー', 2, 500, '発送済み', '2026-09-01'),
  (102, 2, '紅茶', 1, 600, NULL, '2026-09-03'),
  (103, 1, 'マグカップ', 3, 800, '準備中', '2026-09-02'),
  (104, 3, 'コーヒー', 1, 500, '発送済み', '2026-09-04'),
  (105, 2, '紅茶', 4, 600, '準備中', '2026-09-05');`.trim();

export const sqlStart: Lesson[] = [
  {
    id: "sql-table-first",
    track: "sql",
    level: "start",
    chapter: "sql-select",
    order: 1,
    title: "注文表をのぞいてみよう",
    summary: "テーブル・行・列を知り、SELECTで表の中身を読む",
    minutes: 20,
    story: {
      project: "小さな通販店の注文DB",
      incident: "店長から「今日の注文表を一度見せて」と頼まれた",
      outcome: "ordersテーブルの全体を安全に読み出す",
    },
    objectives: [
      { id: "sql-select-all", label: "テーブルの全列をSELECTで読める", conceptIds: ["sql-table", "select-all"] },
    ],
    slides: [
      {
        title: "データベースは整理された棚",
        lead: "通販店では注文を紙ではなくデータベースへ保存します。表の名前が棚、列がラベル、1行が注文1件です。",
        points: ["ordersは注文を置くテーブル", "idやitemは列", "横1行がひとつの注文"],
        diagram: "sql-table",
        storyBeat: "problem",
        talk: [
          { speaker: "beginner", text: "Excelの表と同じように見てよいですか？" },
          { speaker: "engineer", text: "見た目は近いです。SQLでは表に質問して、必要な結果だけ受け取ります。" },
        ],
      },
      {
        title: "SELECTは「見せて」の合図",
        lead: "SELECTの後ろに見たい列、FROMの後ろに棚の名前を書きます。* は「すべての列」という記号です。",
        points: ["SELECT * は全列", "FROM orders はordersから", "最後のセミコロンは文の終わり"],
        diagram: "sql-table",
        code: "SELECT *\nFROM orders;",
        storyBeat: "trace",
        talk: [
          { speaker: "beginner", text: "* は掛け算ですか？" },
          { speaker: "engineer", text: "SELECTの直後では、全列を表す目印です。" },
        ],
      },
      {
        title: "読むだけなら元の表は変わらない",
        lead: "SELECTは棚を眺める操作です。結果という一時的な表が返りますが、保存済みの注文は書き換わりません。",
        points: ["元データと検索結果は別", "結果にも列名と行がある", "まず読む操作から慣れる"],
        diagram: "sql-table",
        storyBeat: "resolution",
        note: "大文字・小文字は多くのDBで区別されませんが、教材ではSQL語を大文字で書きます。",
      },
    ],
    questions: [
      {
        id: "table-row",
        prompt: "注文1件に対応するものはどれですか？",
        kind: "choice",
        options: ["テーブル", "行", "列"],
        answer: "行",
        explain: "1行が注文1件、列はその注文の項目です。",
        hints: ["表の横方向を見ます。", "idからordered_atまでがひとまとまりです。", "横ひとまとまりを何と呼ぶか考えましょう。"],
      },
      {
        id: "select-word",
        prompt: "表からデータを読むとき、最初に書くSQLの単語を入力してください。",
        kind: "input",
        answer: "SELECT",
        aliases: ["select"],
        explain: "SELECTは、指定した列を読み出す命令です。",
        hints: ["英語で「選ぶ」という意味です。", "Sから始まる6文字です。", "FROMより前に置く命令です。"],
      },
      {
        id: "select-all-orders",
        prompt: "ordersテーブルの全列を読み出してください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT
FROM orders;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [
          { id: 101, customer_id: 1, item: "コーヒー", quantity: 2, unit_price: 500, status: "発送済み", ordered_at: "2026-09-01" },
          { id: 102, customer_id: 2, item: "紅茶", quantity: 1, unit_price: 600, status: null, ordered_at: "2026-09-03" },
          { id: 103, customer_id: 1, item: "マグカップ", quantity: 3, unit_price: 800, status: "準備中", ordered_at: "2026-09-02" },
          { id: 104, customer_id: 3, item: "コーヒー", quantity: 1, unit_price: 500, status: "発送済み", ordered_at: "2026-09-04" },
          { id: 105, customer_id: 2, item: "紅茶", quantity: 4, unit_price: 600, status: "準備中", ordered_at: "2026-09-05" },
        ],
        answer: "SELECT * FROM orders;",
        explain: "*を指定するとordersのすべての列が返ります。",
        hints: ["見たい列をSELECTの後ろに置きます。", "今回は列名をひとつずつ並べません。", "全列を表す記号を使います。"],
      },
    ],
  },
  {
    id: "sql-select-columns",
    track: "sql",
    level: "start",
    chapter: "sql-select",
    order: 2,
    title: "必要な列だけ伝票にする",
    summary: "列名を並べ、注文番号と商品名だけを取り出す",
    minutes: 20,
    story: {
      project: "発送担当向けの簡易伝票",
      incident: "全列では情報が多く、商品確認に時間がかかった",
      outcome: "必要な列だけの見やすい結果を作る",
    },
    objectives: [
      { id: "sql-select-columns", label: "複数の列を選んで取得できる", conceptIds: ["select-columns"] },
    ],
    slides: [
      {
        title: "すべて見せると読みにくい",
        lead: "発送担当が欲しいのは注文番号と商品名です。住所も状態も含む全列は、間違いのもとになります。",
        points: ["用途から必要な列を決める", "*は調査には便利", "日常の帳票は列を絞る"],
        diagram: "sql-table",
        storyBeat: "problem",
        talk: [
          { speaker: "beginner", text: "多めに出した方が親切では？" },
          { speaker: "engineer", text: "使わない情報は、探す手間と見間違いを増やします。" },
        ],
      },
      {
        title: "列名はカンマで並べる",
        lead: "SELECTの後ろに列名を左から並べます。結果の列順も、原則として書いた順です。",
        points: ["列と列の間は ,", "最後の列の後ろには不要", "FROMの前までが列の一覧"],
        diagram: "sql-table",
        code: "SELECT id, item\nFROM orders;",
        storyBeat: "trace",
      },
      {
        title: "小さな結果は意図が伝わる",
        lead: "必要な列だけを選ぶと、誰のための一覧かがSQLから読み取れます。データ量も抑えられます。",
        points: ["列名はテーブル定義どおり", "存在しない列はエラー", "選択順が表示順になる"],
        diagram: "sql-table",
        storyBeat: "transfer",
        talk: [
          { speaker: "beginner", text: "item, idと逆に書いたら？" },
          { speaker: "engineer", text: "商品名、注文番号の順で結果に並びます。" },
        ],
      },
    ],
    questions: [
      {
        id: "comma-role",
        prompt: "SELECTで複数の列名を区切る記号はどれですか？",
        kind: "choice",
        options: [",", ".", ":"],
        answer: ",",
        explain: "列名はカンマで区切って並べます。",
        hints: ["文章の読点に近い記号です。", "列名同士の間に1つ置きます。", "id と item の間を思い出しましょう。"],
      },
      {
        id: "from-target",
        prompt: "FROMの直後には、何の名前を書くでしょうか。役割を日本語で入力してください。",
        kind: "input",
        answer: "テーブル名",
        explain: "FROMは、どのテーブルから読むかを指定します。",
        hints: ["データの置かれた棚を指定します。", "SELECTの後ろとは役割が違います。", "ordersのような名前です。"],
      },
      {
        id: "select-id-item",
        prompt: "ordersからidとitemだけを、この順番で読み出してください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT
FROM orders;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [
          { id: 101, item: "コーヒー" },
          { id: 102, item: "紅茶" },
          { id: 103, item: "マグカップ" },
          { id: 104, item: "コーヒー" },
          { id: 105, item: "紅茶" },
        ],
        answer: "SELECT id, item FROM orders;",
        explain: "必要な列名をカンマで区切ると、その列だけが返ります。",
        hints: ["SELECTとFROMの間を埋めます。", "必要な列は2つです。", "問題文の順に列名を並べます。"],
      },
    ],
  },
  {
    id: "sql-where-first",
    track: "sql",
    level: "basic",
    chapter: "sql-filter",
    order: 3,
    title: "発送済みだけを探す",
    summary: "WHEREで条件に合う注文だけを絞り込む",
    minutes: 22,
    story: {
      project: "配送状況の問い合わせ対応",
      incident: "発送済み注文だけを確認したい電話が入った",
      outcome: "状態が一致する行だけを一覧にする",
    },
    objectives: [
      { id: "sql-where-equal", label: "WHEREと=で行を絞り込める", conceptIds: ["where", "comparison"] },
    ],
    slides: [
      {
        title: "列を選ぶだけでは行が多い",
        lead: "SELECTは見たい列を決めます。一方、WHEREは残す行の条件を決めます。縦と横を分けて考えます。",
        points: ["SELECTは列", "WHEREは行", "条件が真の行だけ残る"],
        diagram: "sql-filter",
        storyBeat: "problem",
        talk: [
          { speaker: "beginner", text: "WHEREも列を減らす命令ですか？" },
          { speaker: "engineer", text: "いいえ。条件で注文の件数、つまり行を減らします。" },
        ],
      },
      {
        title: "文字は引用符で囲む",
        lead: "status列が発送済みと等しいかを = で比べます。SQLの文字はシングルクォートで囲みます。",
        points: ["WHEREはFROMの後ろ", "=は等しい", "'発送済み'は文字の値"],
        diagram: "sql-filter",
        code: "SELECT id, item\nFROM orders\nWHERE status = '発送済み';",
        storyBeat: "trace",
      },
      {
        title: "条件は各行へ同じ質問をする",
        lead: "DBは1行ずつstatusを確かめます。条件に合わない行を削除するのではなく、検索結果へ載せないだけです。",
        points: ["元の表は変わらない", "一致する行は複数あり得る", "数値は引用符なしで比べる"],
        diagram: "sql-filter",
        storyBeat: "resolution",
      },
    ],
    questions: [
      {
        id: "where-direction",
        prompt: "WHEREが主に絞り込むものはどれですか？",
        kind: "choice",
        options: ["行", "列", "テーブル名"],
        answer: "行",
        explain: "WHEREは条件に合う行だけを検索結果へ残します。",
        hints: ["SELECTの役割と分けます。", "注文の件数が減ります。", "表の横ひとまとまりを選別します。"],
      },
      {
        id: "equal-operator",
        prompt: "SQLで「等しい」を表す記号を入力してください。",
        kind: "input",
        answer: "=",
        explain: "=で列の値と指定した値を比較します。",
        hints: ["左右に比べる値を置きます。", "算数でも見かける記号です。", "記号は1文字です。"],
      },
      {
        id: "where-shipped",
        prompt: "発送済みの注文について、idとitemを読み出してください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT id, item
FROM orders
WHERE ;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [
          { id: 101, item: "コーヒー" },
          { id: 104, item: "コーヒー" },
        ],
        answer: "SELECT id, item FROM orders WHERE status = '発送済み';",
        explain: "status列を文字列'発送済み'と比較すると2件に絞れます。",
        hints: ["条件に使う列はstatusです。", "等しいかを比較します。", "日本語の値はシングルクォートで囲みます。"],
      },
    ],
  },
  {
    id: "sql-null-and-range",
    track: "sql",
    level: "basic",
    chapter: "sql-filter",
    order: 4,
    title: "未設定と数量を正しく調べる",
    summary: "NULLの意味とIS NULL、ANDを使った複数条件を学ぶ",
    minutes: 24,
    story: {
      project: "注文状態の入力漏れ点検",
      incident: "状態が空の注文を「空文字」で探しても見つからなかった",
      outcome: "NULLを正しく判定し、複数条件も組み合わせる",
    },
    objectives: [
      { id: "sql-null", label: "NULLをIS NULLで判定できる", conceptIds: ["null", "and"] },
    ],
    slides: [
      {
        title: "NULLは空っぽの文字ではない",
        lead: "NULLは「値がない・まだ分からない」という特別な状態です。''という長さ0の文字とも、数値0とも違います。",
        points: ["NULLは未設定", "空文字は設定済みの文字", "0は数値として存在する"],
        diagram: "sql-filter",
        storyBeat: "problem",
        talk: [
          { speaker: "beginner", text: "status = NULLで探せますか？" },
          { speaker: "engineer", text: "NULLは普通の値ではないので、IS NULLと書きます。" },
        ],
      },
      {
        title: "IS NULLで未設定を見つける",
        lead: "等号ではなくIS NULLを使います。反対に、値が入っている行はIS NOT NULLです。",
        points: ["未設定はIS NULL", "設定済みはIS NOT NULL", "= NULLとは書かない"],
        diagram: "sql-filter",
        code: "SELECT id\nFROM orders\nWHERE status IS NULL;",
        storyBeat: "trace",
      },
      {
        title: "ANDは両方を満たす",
        lead: "条件をANDでつなぐと、左右の条件がどちらも真の行だけ残ります。数量が多く、かつ準備中という探し方ができます。",
        points: ["ANDは両方", "ORはどちらか", "条件を小さく読んでからつなぐ"],
        diagram: "sql-filter",
        code: "WHERE quantity >= 3 AND status = '準備中'",
        storyBeat: "transfer",
      },
    ],
    questions: [
      {
        id: "null-meaning",
        prompt: "NULLの説明として最も近いものはどれですか？",
        kind: "choice",
        options: ["数値の0", "未設定・不明", "空文字"],
        answer: "未設定・不明",
        explain: "NULLは値が存在しない、または不明であることを表します。",
        hints: ["値そのものではなく状態です。", "0や空文字とは区別されます。", "まだ入力されていない場面を考えます。"],
      },
      {
        id: "null-check",
        prompt: "NULLかどうかを調べる2語を入力してください。",
        kind: "input",
        answer: "IS NULL",
        aliases: ["is null"],
        explain: "NULLの判定には=ではなくIS NULLを使います。",
        hints: ["等号は使いません。", "2つ目の語はNULLです。", "「〜である」を表す英単語から始まります。"],
      },
      {
        id: "find-unset-status",
        prompt: "statusが未設定の注文のidとitemを読み出してください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT id, item
FROM orders
WHERE status ;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [{ id: 102, item: "紅茶" }],
        answer: "SELECT id, item FROM orders WHERE status IS NULL;",
        explain: "IS NULLを使うと、状態が未設定の注文だけを取得できます。",
        hints: ["未設定は特別な状態です。", "statusを普通の文字とは比較しません。", "=の代わりになる2語を置きます。"],
      },
    ],
  },
  {
    id: "sql-order-by",
    track: "sql",
    level: "basic",
    chapter: "sql-sort",
    order: 5,
    title: "注文を新しい順に並べる",
    summary: "ORDER BYとASC・DESCで結果の順番を決める",
    minutes: 22,
    story: {
      project: "朝会用の注文一覧",
      incident: "登録順の一覧では最新注文を見落とした",
      outcome: "日付を基準に新しい注文から表示する",
    },
    objectives: [
      { id: "sql-order", label: "ORDER BYで昇順・降順を指定できる", conceptIds: ["order-by", "desc"] },
    ],
    slides: [
      {
        title: "順番は保証されていない",
        lead: "ORDER BYを書かない検索結果は、いつもid順とは限りません。見せたい順番はSQLへ明示します。",
        points: ["表の保存順を当てにしない", "並べる基準列を決める", "結果だけが並び替わる"],
        diagram: "sql-sort",
        storyBeat: "problem",
      },
      {
        title: "ORDER BYの後ろがものさし",
        lead: "ASCは小さい順、DESCは大きい順です。日付の文字が年月日形式なら、DESCで新しい日付が先になります。",
        points: ["ASCは昇順", "DESCは降順", "ORDER BYはWHEREより後"],
        diagram: "sql-sort",
        code: "SELECT id, ordered_at\nFROM orders\nORDER BY ordered_at DESC;",
        storyBeat: "trace",
        talk: [
          { speaker: "beginner", text: "元のordersも並び替わりますか？" },
          { speaker: "engineer", text: "検索結果の見え方だけです。保存順を書き換える操作ではありません。" },
        ],
      },
      {
        title: "同じ値なら次の基準を足せる",
        lead: "カンマで列を追加すると、最初の値が同じときだけ次の列で並べます。結果を安定させたいときに便利です。",
        points: ["左の基準が優先", "同値なら右を見る", "idを最後の基準にできる"],
        diagram: "sql-sort",
        code: "ORDER BY ordered_at DESC, id ASC",
        storyBeat: "transfer",
      },
    ],
    questions: [
      {
        id: "desc-meaning",
        prompt: "大きい値から小さい値へ並べる指定はどれですか？",
        kind: "choice",
        options: ["ASC", "DESC", "WHERE"],
        answer: "DESC",
        explain: "DESCは降順で、大きい値や新しい日付を先にします。",
        hints: ["昇順の反対です。", "英語のdescendingの略です。", "Dから始まる4文字です。"],
      },
      {
        id: "sort-clause",
        prompt: "結果を並べ替える句を2語で入力してください。",
        kind: "input",
        answer: "ORDER BY",
        aliases: ["order by"],
        explain: "ORDER BYの後ろに基準列と向きを書きます。",
        hints: ["結果の順序を決めます。", "2語目はBYです。", "Oから始まる句です。"],
      },
      {
        id: "newest-orders",
        prompt: "注文のidとordered_atを、新しい日付が先になるように読み出してください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT id, ordered_at
FROM orders
ORDER BY ordered_at ;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [
          { id: 105, ordered_at: "2026-09-05" },
          { id: 104, ordered_at: "2026-09-04" },
          { id: 102, ordered_at: "2026-09-03" },
          { id: 103, ordered_at: "2026-09-02" },
          { id: 101, ordered_at: "2026-09-01" },
        ],
        answer: "SELECT id, ordered_at FROM orders ORDER BY ordered_at DESC;",
        explain: "ordered_atをDESCで並べると新しい日付が先になります。",
        hints: ["基準列はordered_atです。", "新しい日付は文字としても大きい側です。", "大きい側を先にする向きを指定します。"],
      },
    ],
  },
  {
    id: "sql-limit",
    track: "sql",
    level: "basic",
    chapter: "sql-sort",
    order: 6,
    title: "最新3件だけを取り出す",
    summary: "ORDER BYとLIMITを組み合わせて上位N件を得る",
    minutes: 22,
    story: {
      project: "店長のダッシュボード",
      incident: "全注文を載せたため、画面が長くなった",
      outcome: "並び替えてから必要な件数だけ表示する",
    },
    objectives: [
      { id: "sql-limit", label: "ORDER BYとLIMITで上位件数を取得できる", conceptIds: ["limit", "top-n"] },
    ],
    slides: [
      {
        title: "LIMITだけでは「最新」にならない",
        lead: "LIMITは結果の先頭から件数を切り取るだけです。先に並べ方を決めなければ、どの3件かは意図どおりになりません。",
        points: ["ORDER BYで順番", "LIMITで件数", "2つをセットで考える"],
        diagram: "sql-sort",
        storyBeat: "prediction",
        talk: [
          { speaker: "beginner", text: "LIMIT 3だけで最新3件ですか？" },
          { speaker: "engineer", text: "いいえ。まず最新順を作り、その先頭3件を切り取ります。" },
        ],
      },
      {
        title: "SQLは並べてから切り取る",
        lead: "書く順番はORDER BYの後ろにLIMITです。頭の中では「新しい順の列を作り、先頭を残す」と追います。",
        points: ["LIMITの後ろは件数", "負の件数は使わない", "少ないデータならある分だけ返る"],
        diagram: "sql-sort",
        code: "ORDER BY ordered_at DESC\nLIMIT 3;",
        storyBeat: "trace",
      },
      {
        title: "小さな結果は画面にもやさしい",
        lead: "必要な件数だけ取ると、一覧が読みやすくなります。ただし続きを見る機能では、OFFSETなど別の仕組みも必要です。",
        points: ["まず上位N件を理解する", "取得量を抑えられる", "ページ分けは次の応用"],
        diagram: "sql-sort",
        storyBeat: "resolution",
      },
    ],
    questions: [
      {
        id: "limit-job",
        prompt: "LIMITの役割はどれですか？",
        kind: "choice",
        options: ["列名を変える", "返す行数を制限する", "表を削除する"],
        answer: "返す行数を制限する",
        explain: "LIMITは検索結果の先頭から指定行数だけ返します。",
        hints: ["英語で制限という意味です。", "結果の縦の長さに関係します。", "件数を小さくする役割です。"],
      },
      {
        id: "limit-number",
        prompt: "先頭3件に制限するとき、LIMITの後ろに書く数を入力してください。",
        kind: "input",
        answer: "3",
        explain: "LIMIT 3で先頭から最大3行を返します。",
        hints: ["必要な件数をそのまま書きます。", "0から数え始めません。", "問題文にある件数です。"],
      },
      {
        id: "latest-three",
        prompt: "idとitemを新しい注文順に並べ、先頭3件だけ読み出してください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT id, item
FROM orders
ORDER BY ordered_at
LIMIT ;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [
          { id: 105, item: "紅茶" },
          { id: 104, item: "コーヒー" },
          { id: 102, item: "紅茶" },
        ],
        answer: "SELECT id, item FROM orders ORDER BY ordered_at DESC LIMIT 3;",
        explain: "日付を降順にした後、LIMIT 3で最新3件を残します。",
        hints: ["先にordered_atの並び方を決めます。", "新しい日付を先頭へ移します。", "最後に必要な件数で切り取ります。"],
      },
    ],
  },
  {
    id: "sql-count-sum",
    track: "sql",
    level: "basic",
    chapter: "sql-group",
    order: 7,
    title: "件数と売上をひとつの数字にする",
    summary: "COUNTとSUMで注文全体を集計する",
    minutes: 24,
    story: {
      project: "閉店前の売上確認",
      incident: "店長が注文一覧を手計算していた",
      outcome: "DBに件数と数量合計を計算してもらう",
    },
    objectives: [
      { id: "sql-aggregate", label: "COUNTとSUMの違いを説明し集計できる", conceptIds: ["count", "sum"] },
    ],
    slides: [
      {
        title: "一覧ではなく答えが欲しい",
        lead: "注文を全部表示して数えるより、DBへ「何件？」「数量はいくつ？」と聞けます。複数行をひとつの値へまとめるのが集計です。",
        points: ["COUNTは行数", "SUMは数値の合計", "結果は少ない行になる"],
        diagram: "sql-group",
        storyBeat: "problem",
        talk: [
          { speaker: "beginner", text: "COUNT(quantity)は数量を足しますか？" },
          { speaker: "engineer", text: "足しません。NULLでないquantityが何行あるか数えます。" },
        ],
      },
      {
        title: "COUNT(*)は注文件数",
        lead: "COUNT(*)は条件に合う行を数えます。ASで結果の列に読みやすい別名を付けられます。",
        points: ["COUNT(*)は行数", "ASの後ろは結果列名", "WHEREと組み合わせられる"],
        diagram: "sql-group",
        code: "SELECT COUNT(*) AS order_count\nFROM orders;",
        storyBeat: "trace",
      },
      {
        title: "SUMは列の数値を足す",
        lead: "SUM(quantity)なら全注文の数量を合計します。売上金額にはquantityとunit_priceの積を合計します。",
        points: ["SUMの括弧に数値列", "列同士を計算できる", "別名で数字の意味を伝える"],
        diagram: "sql-group",
        code: "SELECT SUM(quantity) AS total_quantity\nFROM orders;",
        storyBeat: "transfer",
      },
    ],
    questions: [
      {
        id: "aggregate-choice",
        prompt: "注文の行数を求める関数はどれですか？",
        kind: "choice",
        options: ["COUNT", "SUM", "ORDER BY"],
        answer: "COUNT",
        explain: "COUNTは条件に合う行の件数を数えます。",
        hints: ["合計値ではなく件数です。", "英語で「数える」です。", "Cから始まる関数です。"],
      },
      {
        id: "alias-keyword",
        prompt: "結果列へ別名を付けるキーワードを入力してください。",
        kind: "input",
        answer: "AS",
        aliases: ["as"],
        explain: "ASの後ろに結果で表示したい列名を書きます。",
        hints: ["集計結果を読みやすくします。", "2文字のキーワードです。", "COUNT(*)と別名の間に置きます。"],
      },
      {
        id: "sum-quantity",
        prompt: "全注文のquantity合計をtotal_quantityという列名で求めてください。",
        kind: "sql",
        runtime: "sql",
        starter: `SELECT (quantity) AS total_quantity
FROM orders;`,
        sqlSchema: orderSchema,
        sqlSeed: orderSeed,
        sqlExpectedRows: [{ total_quantity: 11 }],
        answer: "SELECT SUM(quantity) AS total_quantity FROM orders;",
        explain: "SUM(quantity)で2+1+3+1+4を計算し、ASで列名を付けます。",
        hints: ["複数行の数値を足す関数が必要です。", "quantityを関数の括弧へ入れます。", "別名はすでにstarterにあります。"],
      },
    ],
  },
];
